import type { NextApiRequest, NextApiResponse } from 'next';
import connectDB from '../../lib/mongodb';
import Student from '../../models/student';

const students = [
  { name: 'Aisha Hussein Ali Almessabi', class: 'G1', division: 'A' },
{ name: 'Aisha Rashed Abdulla Alshehhi', class: 'G1', division: 'A' },
{ name: 'Anood Adil Abdulwahad Alsenaani', class: 'G1', division: 'A' },
{ name: 'Aseel Saleh Ismaeil Alhashmi', class: 'G1', division: 'A' },
{ name: 'Fatma Saif Mohamd Almazrouei', class: 'G1', division: 'A' },
{ name: 'Hamad Abdulsalam Saleh Alameri', class: 'G1', division: 'A' },
{ name: 'Hazza Ali Nasralla Alrejaibi', class: 'G1', division: 'A' },
{ name: 'Hessa Akram Saleh Billeth', class: 'G1', division: 'A' },
{ name: 'Ibrahim Khalil Ibrahim Alzaabi', class: 'G1', division: 'A' },
{ name: 'Khalifa Mohamed Eidha Almenhali', class: 'G1', division: 'A' },
{ name: 'Khalifa Mohamed Mahmoud Aldarmaki', class: 'G1', division: 'A' },
{ name: 'Mariam Mohamed Abdulla Alhashmi', class: 'G1', division: 'A' },
{ name: 'Maryam Fahad Abdulaziz Alseiari', class: 'G1', division: 'A' },
{ name: 'Meera Abdulrahman Yousif Alhammadi', class: 'G1', division: 'A' },
{ name: 'Meera Mohamed Abubaker Almenhali', class: 'G1', division: 'A' },
{ name: 'Mohamed Saleh Abdulla Albreiki', class: 'G1', division: 'A' },
{ name: 'Mohamed Sultan Mohamed Aldahmani', class: 'G1', division: 'A' },
{ name: 'Nayla Mohammad Ahmad Aljumairi', class: 'G1', division: 'A' },
{ name: 'Omair Abdulla Hussain Alhuthaifi', class: 'G1', division: 'A' },
{ name: 'Saeed Khaled Saaeed Alyaqoubi', class: 'G1', division: 'A' },
{ name: 'Saleh Abdulrahman Mohamed Alharthi', class: 'G1', division: 'A' },
{ name: 'Saleh Mohamed Alseiari', class: 'G1', division: 'A' },
{ name: 'Shaikha Yousuf Ali  Alhosani', class: 'G1', division: 'A' },
{ name: 'Shamma Taleb Habib Alhashmi', class: 'G1', division: 'A' },
{ name: 'Shamsa Hasan Ali Alnoman', class: 'G1', division: 'A' },
{ name: 'Sheikha Ahmed Saleh Balalaa', class: 'G1', division: 'A' },
{ name: 'Theyab Ahmed Salem Alhammadi', class: 'G1', division: 'A' },
{ name: 'Yousef Arif Yousof Alhammadi', class: 'G1', division: 'A' },
{ name: 'Zayed Jasem Mohammed Albahlooli', class: 'G1', division: 'A' },
{ name: 'Abdulla Hamad Humaid Almenhali', class: 'G1', division: 'B' },
{ name: 'Ahmed Mohamed Ahmed Alhajjaj', class: 'G1', division: 'B' },
{ name: 'Ali Ibrahim Abdulla Alkhadhar', class: 'G1', division: 'B' },
{ name: 'Alia Abdulla Almansoori', class: 'G1', division: 'B' },
{ name: 'Aseel Abdulrahman Abdulla Alattas', class: 'G1', division: 'B' },
{ name: 'Dheyab Zahid Alblooshi', class: 'G1', division: 'B' },
{ name: 'Faisal Bassam Khries', class: 'G1', division: 'B' },
{ name: 'Fatima Ibrahim Mohamed Alhammadi', class: 'G1', division: 'B' },
{ name: 'Haya Ibraheem Ali Alhammadi', class: 'G1', division: 'B' },
{ name: 'Hazza Ali Ahmed Alhammami', class: 'G1', division: 'B' },
{ name: 'Hessa Hazza Ayoub Alhosani', class: 'G1', division: 'B' },
{ name: 'Hind Haitham Khalil Almas', class: 'G1', division: 'B' },
{ name: 'Khalifa Abdulrahman Marhoon Alhosani', class: 'G1', division: 'B' },
{ name: 'Mahra Saleh Mohamed Dayan', class: 'G1', division: 'B' },
{ name: 'Maitha Belal Ali Alzubaidi', class: 'G1', division: 'B' },
{ name: 'Mansoor Sultan Abdo Alameri', class: 'G1', division: 'B' },
{ name: 'Maryam Faisal Mubarak Aljneibi', class: 'G1', division: 'B' },
{ name: 'Matar Saeed Matar Alneyadi', class: 'G1', division: 'B' },
{ name: 'Mohamed Samer Mohd Soki', class: 'G1', division: 'B' },
{ name: 'Noora Jaber Mubarak Alhajeri', class: 'G1', division: 'B' },
{ name: 'Omar Ammar Ali Albreiki', class: 'G1', division: 'B' },
{ name: 'Osha Khalifa Alhosani', class: 'G1', division: 'B' },
{ name: 'Rahaf Mohamed Almenhali', class: 'G1', division: 'B' },
{ name: 'Saif Abdulhakim Mohamed Alshehhi', class: 'G1', division: 'B' },
{ name: 'Shamma Adnan Alhammadi', class: 'G1', division: 'B' },
{ name: 'Shoug Tariq Ibrahim Alahmadi', class: 'G1', division: 'B' },
{ name: 'Suhail Ali Sultan Alrashedi', class: 'G1', division: 'B' },
{ name: 'Theyab Mohamed Ahmed Alhammadi', class: 'G1', division: 'B' },
{ name: 'Zayed Shawqi Alkatheeri', class: 'G1', division: 'B' },
{ name: 'Zayed Sultan Nasser Almansoori', class: 'G1', division: 'B' },
{ name: 'Abdalla Nasir Aldoud', class: 'G1', division: 'C' },
{ name: 'Abdulla Mohamed Abdulla Alkhemeiri', class: 'G1', division: 'C' },
{ name: 'Abdulla Yousif Malalla Alhammadi', class: 'G1', division: 'C' },
{ name: 'Ahmad Ali Alghareebi', class: 'G1', division: 'C' },
{ name: 'Alayan Bakheet Ateeq Alremeithi', class: 'G1', division: 'C' },
{ name: 'Almaha Hamdan Mohamed Alhosani', class: 'G1', division: 'C' },
{ name: 'Alreem Salem Alaryani', class: 'G1', division: 'C' },
{ name: 'Faisal Abdulla Zayed Almazrouei', class: 'G1', division: 'C' },
{ name: 'Ghalya Hamdan Ahmed Alhammad', class: 'G1', division: 'C' },
{ name: 'Ghanem Abdulrahman Alseiari', class: 'G1', division: 'C' },
{ name: 'Ghayah Ebrahim Mohammed Hussain', class: 'G1', division: 'C' },
{ name: 'Hamad Abdulla Saeed Alhajeri', class: 'G1', division: 'C' },
{ name: 'Hind Abdalla Mohamed Alali', class: 'G1', division: 'C' },
{ name: 'Khalaf Khalid Khalaf Alhammadi', class: 'G1', division: 'C' },
{ name: 'Khalifa Jasem Mohamed Alteneiji', class: 'G1', division: 'C' },
{ name: 'Maitha Ahmed Abdulaziz Alghalebi', class: 'G1', division: 'C' },
{ name: 'Maryam Muneer Habib Hanan', class: 'G1', division: 'C' },
{ name: 'Masoud Marwan Masoud Aldhaheri', class: 'G1', division: 'C' },
{ name: 'Mohamed Saeed Salem Almansoori', class: 'G1', division: 'C' },
{ name: 'Mohamed Yahya Hasan Almarzouqi', class: 'G1', division: 'C' },
{ name: 'Nouf Ahmed Mohamed Alshkeili', class: 'G1', division: 'C' },
{ name: 'Omar Mohamed Ibrahim Alhosani', class: 'G1', division: 'C' },
{ name: 'Saif Ahmed Abdulqader Haisan', class: 'G1', division: 'C' },
{ name: 'Shahad Akram Ali Alemad', class: 'G1', division: 'C' },
{ name: 'Shamma Khaled Abdulla Alhammadi', class: 'G1', division: 'C' },
{ name: 'Sultan Khaled Anees Alhashmi', class: 'G1', division: 'C' },
{ name: 'Yousef Mohamed Yousef  Almarzooqi', class: 'G1', division: 'C' },
{ name: 'Zayed Hamad Abubaker Almenhali', class: 'G1', division: 'C' },
{ name: 'Abdulla Khamis Alhosani', class: 'G1', division: 'D' },
{ name: 'Abdulla Saoud Abdulaziz Alhammadi', class: 'G1', division: 'D' },
{ name: 'Abdullah Jassim Khalil Alhosani', class: 'G1', division: 'D' },
{ name: 'Ahmad Marwan Ahmad Kazim', class: 'G1', division: 'D' },
{ name: 'Alreem Omar Mohamad Alhammadi', class: 'G1', division: 'D' },
{ name: 'Dana Abdulla Salem Haidara', class: 'G1', division: 'D' },
{ name: 'Fatima Khalil Ibrahim Alzaabi', class: 'G1', division: 'D' },
{ name: 'Ghaya Ahmed Yousef Almazrouei', class: 'G1', division: 'D' },
{ name: 'Ilyas Ahmed Hlali', class: 'G1', division: 'D' },
{ name: 'Kaltham Yousif Malalla Alhammadi', class: 'G1', division: 'D' },
{ name: 'Khaled Abdulaziz Khaled Hamza', class: 'G1', division: 'D' },
{ name: 'Khalid Saeed Alameri', class: 'G1', division: 'D' },
{ name: 'Mahra Abdulla Alhammadi', class: 'G1', division: 'D' },
{ name: 'Mahra Hamdan Alhammadi', class: 'G1', division: 'D' },
{ name: 'Maryam Salem Mohamed Albreiki', class: 'G1', division: 'D' },
{ name: 'Meshal Saif Aldharif Alshamsi', class: 'G1', division: 'D' },
{ name: 'Mohammed Ahmed Shareef', class: 'G1', division: 'D' },
{ name: 'Omar Sultan Mohamed Alblooshi', class: 'G1', division: 'D' },
{ name: 'Saif Ahmed Hamood Almahtasap', class: 'G1', division: 'D' },
{ name: 'Salama Abdulazeez Alali', class: 'G1', division: 'D' },
{ name: 'Saud Faisal Hassan Alhosani', class: 'G1', division: 'D' },
{ name: 'Shamma Rashed Mueen Alqubaisi', class: 'G1', division: 'D' },
{ name: 'Sultan Hamad Salem Almansoori', class: 'G1', division: 'D' },
{ name: 'Taif Mohamed Hamdan Alzeyoudi', class: 'G1', division: 'D' },
{ name: 'Yehia Mohamed Sebih', class: 'G1', division: 'D' },
{ name: 'Zayed Sultan Alghafri', class: 'G1', division: 'D' },
{ name: 'Abdulla Bader Jasem Almarzooqi', class: 'G1', division: 'E' },
{ name: 'Ali Abdulla Ali Alshebibi', class: 'G1', division: 'E' },
{ name: 'Dana Ali Yousef Alhosani', class: 'G1', division: 'E' },
{ name: 'Hamad Ahmed Abdulrahman Albreiki', class: 'G1', division: 'E' },
{ name: 'Hind Mohamed Abdulla Almahrooqi', class: 'G1', division: 'E' },
{ name: 'Khaled Ahmed Saif Albusaeedi', class: 'G1', division: 'E' },
{ name: 'Khalid Tariq Almarzooqi', class: 'G1', division: 'E' },
{ name: 'Khalifa Salem Abdulla Alhashmi', class: 'G1', division: 'E' },
{ name: 'Maitha Mahmood Alhashmi', class: 'G1', division: 'E' },
{ name: 'Maitha Mohamed Mahmmoud Alhussaini', class: 'G1', division: 'E' },
{ name: 'Maryam Yousif Darwish Alhosani', class: 'G1', division: 'E' },
{ name: 'Metab Abdulla Abdulrahman Alhashmi', class: 'G1', division: 'E' },
{ name: 'Mohammed Ahmed Alkalbani', class: 'G1', division: 'E' },
{ name: 'Mohammed Walied Elryeh Ahmed', class: 'G1', division: 'E' },
{ name: 'Nasser Saif Rashed Aldahmani', class: 'G1', division: 'E' },
{ name: 'Omer Mohamed Nooruddin Kazim', class: 'G1', division: 'E' },
{ name: 'Rawdha Jaafar Alfarsi', class: 'G1', division: 'E' },
{ name: 'Reem Abdulla Alalawi', class: 'G1', division: 'E' },
{ name: 'Roya Saeed Almuharrami', class: 'G1', division: 'E' },
{ name: 'Saeed Abdulla Saeed Alameri', class: 'G1', division: 'E' },
{ name: 'Saif Ali Baniwael', class: 'G1', division: 'E' },
{ name: 'Saif Khaled Rabeea Alremeithi', class: 'G1', division: 'E' },
{ name: 'Salama Majed Alblooshi', class: 'G1', division: 'E' },
{ name: 'Salem Sulaiman Alhanaee', class: 'G1', division: 'E' },
{ name: 'Shahd Taher Easa Alnuaimi', class: 'G1', division: 'E' },
{ name: 'Shamma Rashed Obaid Alremeithi', class: 'G1', division: 'E' },
{ name: 'Stylianos Papathanasiou', class: 'G1', division: 'E' },
{ name: 'Taif Sultan Abdo Alameri', class: 'G1', division: 'E' },
{ name: 'Thamer Husain Ali Alzubaidi', class: 'G1', division: 'E' },
{ name: 'Zayed Mohamed Alhosani', class: 'G1', division: 'E' },
{ name: 'Abdelrahman Reda Elmaasry', class: 'G1', division: 'F' },
{ name: 'Adam Alexander Souto Diaz', class: 'G1', division: 'F' },
{ name: 'Ahmed Ibrahim Almarashda', class: 'G1', division: 'F' },
{ name: 'Ali Ibrahim Alobeidli', class: 'G1', division: 'F' },
{ name: 'Ali Omar Rajab Alhosani', class: 'G1', division: 'F' },
{ name: 'Altarf Ali Saleh Almansoori', class: 'G1', division: 'F' },
{ name: 'Alyazia Humaid Ismaeel Alhammadi', class: 'G1', division: 'F' },
{ name: 'Dana Hamad Ahmed Alhammadi', class: 'G1', division: 'F' },
{ name: 'Eissa Mohamed Almarzooqi', class: 'G1', division: 'F' },
{ name: 'Fatima Manea Rashid Alyammahi', class: 'G1', division: 'F' },
{ name: 'Hala Yaslem Mabrook Albreiki', class: 'G1', division: 'F' },
{ name: 'Hamad Husain Ibrahim Alhammadi', class: 'G1', division: 'F' },
{ name: 'Hoor Abdullah Mohamed Alhosani', class: 'G1', division: 'F' },
{ name: 'Khaled Ahmed Almessabi', class: 'G1', division: 'F' },
{ name: 'Khaled Bakheet Ateeq Alremeithi', class: 'G1', division: 'F' },
{ name: 'Khalifa Ahmed Alhajri', class: 'G1', division: 'F' },
{ name: 'Maitha Nayef Mohammed Albreiki', class: 'G1', division: 'F' },
{ name: 'Maitha Omar Almemari', class: 'G1', division: 'F' },
{ name: 'Meera Abdulla Mahmoud Alsheebani', class: 'G1', division: 'F' },
{ name: 'Mohamed Adel Mohamed Alhosani', class: 'G1', division: 'F' },
{ name: 'Rashed Ali Khamis Alhammadi', class: 'G1', division: 'F' },
{ name: 'Saeed Ahmed Alhammadi', class: 'G1', division: 'F' },
{ name: 'Saif Marwan Abdulla Almarzooqi', class: 'G1', division: 'F' },
{ name: 'Salama Khaled Omar Bazuhair', class: 'G1', division: 'F' },
{ name: 'Salama Salem Alameri', class: 'G1', division: 'F' },
{ name: 'Salem Jadeed Abdulla Alrashdi', class: 'G1', division: 'F' },
{ name: 'Shamma Saeed Ali Alhosani', class: 'G1', division: 'F' },
{ name: 'Taif Adel Altaheri', class: 'G1', division: 'F' },
{ name: 'Theyab Majed Aljaberi', class: 'G1', division: 'F' },
{ name: 'Zayed Ahmed Saleh Alhammadi', class: 'G1', division: 'F' },
{ name: 'Abdullah Sultan Abdulla Alsaqqaf', class: 'G1', division: 'G' },
{ name: 'Aisha Abdulazeiz Alyammahi', class: 'G1', division: 'G' },
{ name: 'Aljamila Amer Altamimi', class: 'G1', division: 'G' },
{ name: 'Alreem Karama Yaser Almenhali', class: 'G1', division: 'G' },
{ name: 'Amer Mohamed Abdeljalil Alzarooni', class: 'G1', division: 'G' },
{ name: 'Dana Husain Naser Alhayeed', class: 'G1', division: 'G' },
{ name: 'Ghaya Mohamed Ahmed Alnaqbi', class: 'G1', division: 'G' },
{ name: 'Hamad Mohamad Abdulrahman Alhammadi', class: 'G1', division: 'G' },
{ name: 'Hamda Barak Nasir Alkarbi', class: 'G1', division: 'G' },
{ name: 'Jawhara Jamal Ali Alharbi', class: 'G1', division: 'G' },
{ name: 'Khaled Sultan Abdulla Alsaqqaf', class: 'G1', division: 'G' },
{ name: 'Khalid Ahmed Abdulla Alkhemeiri', class: 'G1', division: 'G' },
{ name: 'Khalifa Abdulmalek Mohamed Almessabi', class: 'G1', division: 'G' },
{ name: 'Mahra Abdulla Alblooshi', class: 'G1', division: 'G' },
{ name: 'Malak Abdulrahman Yousif Alhammadi', class: 'G1', division: 'G' },
{ name: 'Mansour Abdullah Alhamadi', class: 'G1', division: 'G' },
{ name: 'Mayed Abdulla Hassan Alblooshi', class: 'G1', division: 'G' },
{ name: 'Mohamed Fares Abdulla Alharthi', class: 'G1', division: 'G' },
{ name: 'Mubarak Ali Mubarak Ban Boraik', class: 'G1', division: 'G' },
{ name: 'Mubarak Khalifa Hashel Almeghairi', class: 'G1', division: 'G' },
{ name: 'Naser Ali Mubarak Almansoori', class: 'G1', division: 'G' },
{ name: 'Rashed Saif Rashed Aldahmani', class: 'G1', division: 'G' },
{ name: 'Saif Fahad Almahri', class: 'G1', division: 'G' },
{ name: 'Saif Mashal Mohamed Alqahtani', class: 'G1', division: 'G' },
{ name: 'Sarah Ibrahim Khalil Alhammadi', class: 'G1', division: 'G' },
{ name: 'Shaikha Omar Almemari', class: 'G1', division: 'G' },
{ name: 'Suhail Khalifa Nasralla Alrejaibi', class: 'G1', division: 'G' },
{ name: 'Sultan Faiez Abdulla Alsulaimi', class: 'G1', division: 'G' },
{ name: 'Zayed Ahmed Yousef Alobeidli', class: 'G1', division: 'G' },
{ name: 'Abdulla Eissa Alattas', class: 'G1', division: 'H' },
{ name: 'Alia Hasan Alali', class: 'G1', division: 'H' },
{ name: 'Alreem Hamad Saif', class: 'G1', division: 'H' },
{ name: 'Alyazia Suood Abdulaziz Alshehhi', class: 'G1', division: 'H' },
{ name: 'Dhabiah Ibrahim Alhammadi', class: 'G1', division: 'H' },
{ name: 'Fahad Khaled Ibrahem  Alhammadi', class: 'G1', division: 'H' },
{ name: 'Fatima Hassan Ali Almarashda', class: 'G1', division: 'H' },
{ name: 'Hamdan Abdulla Faraj Alhajeri', class: 'G1', division: 'H' },
{ name: 'Hamdan Khalid Saleh Binzubaa', class: 'G1', division: 'H' },
{ name: 'Hanadi Mathkar Fahad Alharthi', class: 'G1', division: 'H' },
{ name: 'Jood Adel Abdulla Aljaberi', class: 'G1', division: 'H' },
{ name: 'Khalid Adnan Ahmed Almaskari', class: 'G1', division: 'H' },
{ name: 'Mahra Yousef Alhammadi', class: 'G1', division: 'H' },
{ name: 'Mansour Mohamad Salem Alhosani', class: 'G1', division: 'H' },
{ name: 'Mansour Mohamed Abubaker Almenhali', class: 'G1', division: 'H' },
{ name: 'Maria Nasser Hassan Alhammadi', class: 'G1', division: 'H' },
{ name: 'Meera Faisal Mohamed Aljaberi', class: 'G1', division: 'H' },
{ name: 'Mohamed Sultan Khaled Alobaidi', class: 'G1', division: 'H' },
{ name: 'Nahyan Nasser Rashed Almansoori', class: 'G1', division: 'H' },
{ name: 'Rashid Mohamed Ibrahim Almarzooqi', class: 'G1', division: 'H' },
{ name: 'Saif Mohammed Ahmad Darwish', class: 'G1', division: 'H' },
{ name: 'Saif Sultan Ahmad Almheiri', class: 'G1', division: 'H' },
{ name: 'Shahad Ahmad Alyafei', class: 'G1', division: 'H' },
{ name: 'Shahad Amer Mohamed Alhammadi', class: 'G1', division: 'H' },
{ name: 'Shamsa Khaled Ali Almarzooqi', class: 'G1', division: 'H' },
{ name: 'Shamsa Mohamed Saleh Almansoori', class: 'G1', division: 'H' },
{ name: 'Sultan Khalifa Nasralla Alrejaibi', class: 'G1', division: 'H' },
{ name: 'Zayed Eissa Mohamed Alhosani', class: 'G1', division: 'H' },
{ name: 'Zayed Sultan Almazrouei', class: 'G1', division: 'H' },
{ name: 'Abdulla Omar Alnuaimi', class: 'G2', division: 'A' },
{ name: 'Ahmed Yasser Humaidan', class: 'G2', division: 'A' },
{ name: 'Alma Ahmed Badr', class: 'G2', division: 'A' },
{ name: 'Alyazia Ahmed Abdulla Alameri', class: 'G2', division: 'A' },
{ name: 'Dana Faisal Rashad Alafeefi', class: 'G2', division: 'A' },
{ name: 'Fatima Mohamed Alhashmi', class: 'G2', division: 'A' },
{ name: 'Hamad Mohamed Abdulla Alhashmi', class: 'G2', division: 'A' },
{ name: 'Hamda Ahmed Khadem Almansoori', class: 'G2', division: 'A' },
{ name: 'Hamdan Samer Alhadhrami', class: 'G2', division: 'A' },
{ name: 'Hessa Falah Naser Alawlaqi', class: 'G2', division: 'A' },
{ name: 'Kenzy Talha Hadaqi', class: 'G2', division: 'A' },
{ name: 'Khaled Ali Mohamed Alsaqqaf', class: 'G2', division: 'A' },
{ name: 'Kinda Mohammed Fairooz Alkendi', class: 'G2', division: 'A' },
{ name: 'Mariam Mohamed Eissa Alzaabi', class: 'G2', division: 'A' },
{ name: 'Mashael Mohamed Abdulqader Alhammadi', class: 'G2', division: 'A' },
{ name: 'Mohamed Husain Naser Alhayeed', class: 'G2', division: 'A' },
{ name: 'Mohameed Abdulla Mohamed Alsalmi', class: 'G2', division: 'A' },
{ name: 'Nahyan Omran Alhammadi', class: 'G2', division: 'A' },
{ name: 'Naya Alsaid', class: 'G2', division: 'A' },
{ name: 'Noura Mohamed Ahmed Alali', class: 'G2', division: 'A' },
{ name: 'Omer Ahmed Ibrahim Ali', class: 'G2', division: 'A' },
{ name: 'Reem Saeed Alkaabi', class: 'G2', division: 'A' },
{ name: 'Rouda Mohamed Abubaker Almenhali', class: 'G2', division: 'A' },
{ name: 'Rwdah Khaled Sulaiman Almenhali', class: 'G2', division: 'A' },
{ name: 'Sara Abdulla Aqeel Alshehhi', class: 'G2', division: 'A' },
{ name: 'Shamsa Fahad Haitham Jaber', class: 'G2', division: 'A' },
{ name: 'Zayed Hamad Alameri', class: 'G2', division: 'A' },
{ name: 'Zlikah Shawqi Alkatheeri', class: 'G2', division: 'A' },
{ name: 'Abdelaziz Marwan Mohammed Alkaabi', class: 'G2', division: 'B' },
{ name: 'Afra Hamad Mohamed Altashi', class: 'G2', division: 'B' },
{ name: 'Ahmed Abdulaziz Alali', class: 'G2', division: 'B' },
{ name: 'Ahmed Yousef Alzuriqi', class: 'G2', division: 'B' },
{ name: 'Amirah Mohammed Almanhaly', class: 'G2', division: 'B' },
{ name: 'Dhai Waleed Yaqoub Binhuwaidin', class: 'G2', division: 'B' },
{ name: 'Eissa Hamad Ali Alsereidi', class: 'G2', division: 'B' },
{ name: 'Faisal Khaled Abdullah Alamoudi', class: 'G2', division: 'B' },
{ name: 'Falah Ahmed Helal Aldhanhani', class: 'G2', division: 'B' },
{ name: 'Hamad Rashed Alghafri', class: 'G2', division: 'B' },
{ name: 'Hamed Mohamed Abdulrahman Alhammadi', class: 'G2', division: 'B' },
{ name: 'Haya Fahed Abbas Alhosani', class: 'G2', division: 'B' },
{ name: 'Hazza Ahmed Alameri', class: 'G2', division: 'B' },
{ name: 'Humaid Abdulla Omar Bazuhair', class: 'G2', division: 'B' },
{ name: 'Khalifa Zayed Ahmed Alansi', class: 'G2', division: 'B' },
{ name: 'Latifah Khaled Mohamed Almarzooqi', class: 'G2', division: 'B' },
{ name: 'Mahra Waleed Rashed Alzaabi', class: 'G2', division: 'B' },
{ name: 'Mohammed  Khalifa Aldhaheri', class: 'G2', division: 'B' },
{ name: 'Mohammed Amer Nasralla Alrejaibi', class: 'G2', division: 'B' },
{ name: 'Nouf Nabeel Alnaqbi', class: 'G2', division: 'B' },
{ name: 'Rashed Saleh Abdulla Albreiki', class: 'G2', division: 'B' },
{ name: 'Rawdha Ali Shadad', class: 'G2', division: 'B' },
{ name: 'Rawdha Thani Abdulla Alali', class: 'G2', division: 'B' },
{ name: 'Saqer Mahmoud Ismaeel Alhammadi', class: 'G2', division: 'B' },
{ name: 'Sara Ahmed Mohammed Alblooshi', class: 'G2', division: 'B' },
{ name: 'Shamsa Helal Alhadhrami', class: 'G2', division: 'B' },
{ name: 'Shamsa Yousif Mohamed Aldhuhoori', class: 'G2', division: 'B' },
{ name: 'Theyab Ali Khamis Alhammadi', class: 'G2', division: 'B' },
{ name: 'Wadha Salem Dhafer Alhajeri', class: 'G2', division: 'B' },
{ name: 'Zayed Salem Alamarashda', class: 'G2', division: 'B' },
{ name: 'Abdulla Saleh Abdulla Alhammadi', class: 'G2', division: 'C' },
{ name: 'Afra Saleh Ahmed Alsaadi', class: 'G2', division: 'C' },
{ name: 'Alameera Mubarak Alrashdi', class: 'G2', division: 'C' },
{ name: 'Almaha Faisal Almansoori', class: 'G2', division: 'C' },
{ name: 'Dana Mohamed Maaroof Baobaid', class: 'G2', division: 'C' },
{ name: 'Dhabia Mohamed Alqubaisi', class: 'G2', division: 'C' },
{ name: 'Hamdan Mohamed Almakhmari', class: 'G2', division: 'C' },
{ name: 'Hamed Taha Husain Alhashmi', class: 'G2', division: 'C' },
{ name: 'Hassan Ahmed Hamed Alaydaroos', class: 'G2', division: 'C' },
{ name: 'Humaid Faisal Mohamed Alzaidi', class: 'G2', division: 'C' },
{ name: 'Humaid Yaser Adel Alalawi', class: 'G2', division: 'C' },
{ name: 'Layla Falah Hamood Alqahtani', class: 'G2', division: 'C' },
{ name: 'Maitha Hasan Ali Alhosani', class: 'G2', division: 'C' },
{ name: 'Mireh Mohammed Almanhaly', class: 'G2', division: 'C' },
{ name: 'Mouza Saif Mohamed Almazrouei', class: 'G2', division: 'C' },
{ name: 'Mubarak Salem Mubarak Almenhali', class: 'G2', division: 'C' },
{ name: 'Noor Waheb Dawod', class: 'G2', division: 'C' },
{ name: 'Obaid Rashed Obaid Alremeithi', class: 'G2', division: 'C' },
{ name: 'Qasayed Mohamed Aldarmaki', class: 'G2', division: 'C' },
{ name: 'Rawdah Humaid Rashed Alyammahi', class: 'G2', division: 'C' },
{ name: 'Shamsa Yousif Alkhoori', class: 'G2', division: 'C' },
{ name: 'Sheikha Mohammed Abdulaziz Alawadi', class: 'G2', division: 'C' },
{ name: 'Shouq Ali Alrashdi', class: 'G2', division: 'C' },
{ name: 'Sultan Abdulla Hamad Alebri', class: 'G2', division: 'C' },
{ name: 'Sultan Qarran Rashed Almansoori', class: 'G2', division: 'C' },
{ name: 'Theyab Naser Almansoori', class: 'G2', division: 'C' },
{ name: 'Zayed Abdulla Alshehhi', class: 'G2', division: 'C' },
{ name: 'Zayed Yahya Hussein Abdullah', class: 'G2', division: 'C' },
{ name: 'Aisha Mohammed Abbas Abdulrasool', class: 'G2', division: 'D' },
{ name: 'Ali Naji Mubarak Alkarbi', class: 'G2', division: 'D' },
{ name: 'Almaha Mahmood Alkhyeli', class: 'G2', division: 'D' },
{ name: 'Dalal Khalid Saleh Binzubaa', class: 'G2', division: 'D' },
{ name: 'Hareb Abdulla Eissa Alhosani', class: 'G2', division: 'D' },
{ name: 'Hazza Obaid Rashed Almehrzi', class: 'G2', division: 'D' },
{ name: 'Hind Abdulla Mattar Alhosani', class: 'G2', division: 'D' },
{ name: 'Hind Mohamed Alhmoudi', class: 'G2', division: 'D' },
{ name: 'Ibraheem Khalid Ibraheem Alhosani', class: 'G2', division: 'D' },
{ name: 'Jasim Ibrahim Jasim Alhammadi', class: 'G2', division: 'D' },
{ name: 'Layla Mohamed Salah Mashaly', class: 'G2', division: 'D' },
{ name: 'Maitha Salman Mohamed Alhammadi', class: 'G2', division: 'D' },
{ name: 'Majed Zaid Mohamed Alharthi', class: 'G2', division: 'D' },
{ name: 'Mansour Ahmed Mansour  Alwahedi', class: 'G2', division: 'D' },
{ name: 'Mira Abdulrahman Mohamed Alkaabi', class: 'G2', division: 'D' },
{ name: 'Mohamed Rashed Hasan Alzaabi', class: 'G2', division: 'D' },
{ name: 'Mohammad Osama Alsharef', class: 'G2', division: 'D' },
{ name: 'Muhammad Mahfooz Abdullah', class: 'G2', division: 'D' },
{ name: 'Noor Khalid Abdalla Aldhuhoori', class: 'G2', division: 'D' },
{ name: 'Noura Mohamed Alhmoudi', class: 'G2', division: 'D' },
{ name: 'Qamar Mahmoud Salem Almahri', class: 'G2', division: 'D' },
{ name: 'Saif Alayan Abdulla Alremeithi', class: 'G2', division: 'D' },
{ name: 'Saoud Faisal Binamro', class: 'G2', division: 'D' },
{ name: 'Sara Hussain Aqeel Almehairbi', class: 'G2', division: 'D' },
{ name: 'Shaikha Rashed Ibrahim Alhosani', class: 'G2', division: 'D' },
{ name: 'Shikah Salem Mubarak Alrashdi', class: 'G2', division: 'D' },
{ name: 'Sultan Ahmed Ali Alyafei', class: 'G2', division: 'D' },
{ name: 'Abdulrahman Ismail Saleh Mohamed', class: 'G2', division: 'E' },
{ name: 'Ali Omar Ali Aldhanhani', class: 'G2', division: 'E' },
{ name: 'Aljawhara Ali Bani Ebrahim', class: 'G2', division: 'E' },
{ name: 'Eissa Bader Alawlaqi', class: 'G2', division: 'E' },
{ name: 'Ghaith Jumaa Ghareeb Alqemzi', class: 'G2', division: 'E' },
{ name: 'Ghala Hamad Mohammed Alblooshi', class: 'G2', division: 'E' },
{ name: 'Humaid Abdulla Almurshidi', class: 'G2', division: 'E' },
{ name: 'Ibrahim Mohammed Shash', class: 'G2', division: 'E' },
{ name: 'Jood Waed Mohammed Alafifi', class: 'G2', division: 'E' },
{ name: 'Laila Musallam Mohamed Alkatheeri', class: 'G2', division: 'E' },
{ name: 'Luluwa Falah Hamood Alqahtani', class: 'G2', division: 'E' },
{ name: 'Mahra Mohamed Naeem Alansaari', class: 'G2', division: 'E' },
{ name: 'Mariam Faisal Rashed Almarar', class: 'G2', division: 'E' },
{ name: 'Mezna Amer Salem Alameri', class: 'G2', division: 'E' },
{ name: 'Mohamed Ramzi Husain Alkaf', class: 'G2', division: 'E' },
{ name: 'Mohamed Saif Hasan Almarzooqi', class: 'G2', division: 'E' },
{ name: 'Mohamed Yasir Mohamed Ali', class: 'G2', division: 'E' },
{ name: 'Mouza Hashem Abdulrahman Altamimi', class: 'G2', division: 'E' },
{ name: 'Nahyan Adel A.Almohanna', class: 'G2', division: 'E' },
{ name: 'Nouf Ayman Mohammed Aldhuhoori', class: 'G2', division: 'E' },
{ name: 'Noura Abdulrahman Salah Alhasani', class: 'G2', division: 'E' },
{ name: 'Saif Yaseen Ahmed Samtar', class: 'G2', division: 'E' },
{ name: 'Shaikha Saqer Mohamed Almansoori', class: 'G2', division: 'E' },
{ name: 'Shamma Ali Alrashdi', class: 'G2', division: 'E' },
{ name: 'Sultan Ali Ahmad Almarzooqi', class: 'G2', division: 'E' },
{ name: 'Tahani Saeed Yousif Aldhuhoori', class: 'G2', division: 'E' },
{ name: 'Theyab Majed Suliman Almarzooqi', class: 'G2', division: 'E' },
{ name: 'Zayed Mansour Alremeithi', class: 'G2', division: 'E' },
{ name: 'Abdulaziz Ghanem Alhammadi', class: 'G2', division: 'F' },
{ name: 'Abdulla Khalid Alzaidi', class: 'G2', division: 'F' },
{ name: 'Abdulla Majdaldeen Mohamed', class: 'G2', division: 'F' },
{ name: 'Ahmed Adnan Ahmed Almaskari', class: 'G2', division: 'F' },
{ name: 'Alhanoof Abdulrahman Alsheaibi', class: 'G2', division: 'F' },
{ name: 'Almahra Rashed Meferrej Alameri', class: 'G2', division: 'F' },
{ name: 'Amro Rabee Douier', class: 'G2', division: 'F' },
{ name: 'Eissa Ahmed Alzaabi', class: 'G2', division: 'F' },
{ name: 'Faris Sultan Alhelali', class: 'G2', division: 'F' },
{ name: 'Ghanem Saeed Alhemeiri', class: 'G2', division: 'F' },
{ name: 'Ghaya Khalid Alhosani', class: 'G2', division: 'F' },
{ name: 'Hajer Marwan Amer Alsaleemi', class: 'G2', division: 'F' },
{ name: 'Hamad Ameen Abdulla Alhosani', class: 'G2', division: 'F' },
{ name: 'Hind Rashid Alnaqbi', class: 'G2', division: 'F' },
{ name: 'Hmdah Hamad Salmeen Alameri', class: 'G2', division: 'F' },
{ name: 'Hour Mohammed Alwahedi', class: 'G2', division: 'F' },
{ name: 'Khalifa Khalid Alhosani', class: 'G2', division: 'F' },
{ name: 'Marya Abdullah Alnaqbi', class: 'G2', division: 'F' },
{ name: 'Meera Ahmad Alahmadi', class: 'G2', division: 'F' },
{ name: 'Mohamed Ahmed Almarzooqi', class: 'G2', division: 'F' },
{ name: 'Mohamed Omar Husain Alakberi', class: 'G2', division: 'F' },
{ name: 'Salem Mohamed Ahmed Alhosani', class: 'G2', division: 'F' },
{ name: 'Shamma Ramzi Husain Alkaf', class: 'G2', division: 'F' },
{ name: 'Shamsa Sultan Almarzooqi', class: 'G2', division: 'F' },
{ name: 'Sultan Mansour Alremeithi', class: 'G2', division: 'F' },
{ name: 'Talia M. M. Sawafta', class: 'G2', division: 'F' },
{ name: 'Zayed Thamer Alameri', class: 'G2', division: 'F' },
{ name: 'Aldanah Humaid Alameemi', class: 'G3', division: 'A' },
{ name: 'Ali Hassan Alhammadi', class: 'G3', division: 'A' },
{ name: 'Alia Abdulla Almheiri', class: 'G3', division: 'A' },
{ name: 'Alia Arif Hasan Almarzooqi', class: 'G3', division: 'A' },
{ name: 'Alya Abdulla Mohamed Alamri', class: 'G3', division: 'A' },
{ name: 'Dana Ali Alhammadi', class: 'G3', division: 'A' },
{ name: 'Dana Barak Nasir Alkarbi', class: 'G3', division: 'A' },
{ name: 'Hamad Omar Alkhoori', class: 'G3', division: 'A' },
{ name: 'Hamdan Tareq Alhammadi', class: 'G3', division: 'A' },
{ name: 'Hessa Bader Ibrahim Alhammadi', class: 'G3', division: 'A' },
{ name: 'Hessa Mohamed Musabbah Almeeshani', class: 'G3', division: 'A' },
{ name: 'Hind Ahmed Abdulrahman Albreiki', class: 'G3', division: 'A' },
{ name: 'Hind Waleed Ismaeil Alhammadi', class: 'G3', division: 'A' },
{ name: 'Hoor Abdulla Alkhouri', class: 'G3', division: 'A' },
{ name: 'Khalid Hazza Abdulrahim Alhammadi', class: 'G3', division: 'A' },
{ name: 'Lolwa Yaqoub Yousif Alzaabi', class: 'G3', division: 'A' },
{ name: 'Mariam Ali Mohamed Alhammadi', class: 'G3', division: 'A' },
{ name: 'Meznah Mohamed Alhosani', class: 'G3', division: 'A' },
{ name: 'Mohamed Khalid Almarzooqi', class: 'G3', division: 'A' },
{ name: 'Mohammed Hamoud Aljaberi', class: 'G3', division: 'A' },
{ name: 'Mouza Ali Abdalla Alhosani', class: 'G3', division: 'A' },
{ name: 'Nahyan Abdulla Saeed', class: 'G3', division: 'A' },
{ name: 'Nhyan Abdulla Awad Alshamsi', class: 'G3', division: 'A' },
{ name: 'Noura Abdulrahman Haroun Alhammadi', class: 'G3', division: 'A' },
{ name: 'Rakan Abdulla Aljaberi', class: 'G3', division: 'A' },
{ name: 'Salama Mohamed Rashed Almheiri', class: 'G3', division: 'A' },
{ name: 'Salem Abdulla Alhammadi', class: 'G3', division: 'A' },
{ name: 'Shamma Hamad Alhammadi', class: 'G3', division: 'A' },
{ name: 'Shamsa Saoud Abdulazeez Binsafwan', class: 'G3', division: 'A' },
{ name: 'Zayed Khaled Khadher Alsalehi', class: 'G3', division: 'A' },
{ name: 'Abdulla Khaled Abdulla Alhammadi', class: 'G3', division: 'B' },
{ name: 'Abdulla Zaher Alseiari', class: 'G3', division: 'B' },
{ name: 'Ahmed Waleed Borhan Alrashdi', class: 'G3', division: 'B' },
{ name: 'Ahmed Yousef Alhammadi', class: 'G3', division: 'B' },
{ name: 'Alya Eissa Salem Aljneibi', class: 'G3', division: 'B' },
{ name: 'Dhabia Mohamed Almarzooqi', class: 'G3', division: 'B' },
{ name: 'Fatima Mohamed Alhosani', class: 'G3', division: 'B' },
{ name: 'Ghaya Khaleefa Almarzooqi', class: 'G3', division: 'B' },
{ name: 'Hamad Husain Naser Alhayeed', class: 'G3', division: 'B' },
{ name: 'Hamdan Hamad Almehairbi', class: 'G3', division: 'B' },
{ name: 'Hassan Abdulla Hassan Alblooshi', class: 'G3', division: 'B' },
{ name: 'Hazza Abdulrahman Mohamed Alseiari', class: 'G3', division: 'B' },
{ name: 'Hessa Hassan Alblooshi', class: 'G3', division: 'B' },
{ name: 'Khalifa Hasan Mohammed Maanna', class: 'G3', division: 'B' },
{ name: 'Khalifa Mohamed Almakhmari', class: 'G3', division: 'B' },
{ name: 'Maha Sabri Alseyabi', class: 'G3', division: 'B' },
{ name: 'Mansour Yousuf Alhosani', class: 'G3', division: 'B' },
{ name: 'Mohamed Ibrahim Alhammadi', class: 'G3', division: 'B' },
{ name: 'Mohamed Saif Salem Alhosani', class: 'G3', division: 'B' },
{ name: 'Mohamed Samer Alhadhrami', class: 'G3', division: 'B' },
{ name: 'Mohammed Ali Nasralla Alrejaibi', class: 'G3', division: 'B' },
{ name: 'Obaid Hassan Ali Almarashda', class: 'G3', division: 'B' },
{ name: 'Salem Hamad Saif', class: 'G3', division: 'B' },
{ name: 'Sara Mohammed Alameri', class: 'G3', division: 'B' },
{ name: 'Shamma Ahmed Alshkeili', class: 'G3', division: 'B' },
{ name: 'Shamma Khalifa Alhammadi', class: 'G3', division: 'B' },
{ name: 'Sultan Khaled Mohamed Almarzooqi', class: 'G3', division: 'B' },
{ name: 'Sultan Mutaab Hamad Almarri', class: 'G3', division: 'B' },
{ name: 'Theyab Mohamed Alhilali', class: 'G3', division: 'B' },
{ name: 'Wadeema Khaled Almahri', class: 'G3', division: 'B' },
{ name: 'Abdulla Rashed Dhahi Alremeithi', class: 'G3', division: 'C' },
{ name: 'Abdulrahman Mohamed Nooruddin Kazim', class: 'G3', division: 'C' },
{ name: 'Ali Ebrahim Ali Alkarbi', class: 'G3', division: 'C' },
{ name: 'Alia Salem Abdulraheem Alhammadi', class: 'G3', division: 'C' },
{ name: 'Alkadi Humaid Ismaeel Alhammadi', class: 'G3', division: 'C' },
{ name: 'Alyazya Hamad Jasem Alhosani', class: 'G3', division: 'C' },
{ name: 'Dana Adnan Ahmed Almaskari', class: 'G3', division: 'C' },
{ name: 'Deema Ali Ziad Alkharoossi', class: 'G3', division: 'C' },
{ name: 'Hadef Mohammed Alkaabi', class: 'G3', division: 'C' },
{ name: 'Hamdan Ahmed Abdulla Alhammadi', class: 'G3', division: 'C' },
{ name: 'Jad Jawad Altalahmeh', class: 'G3', division: 'C' },
{ name: 'Khalifa Khaled Hamdan Almurshidi', class: 'G3', division: 'C' },
{ name: 'Maha Sami Abdullah Alkhuzairi', class: 'G3', division: 'C' },
{ name: 'Maryam Abdulla Jasem Alhosani', class: 'G3', division: 'C' },
{ name: 'Mohamed Saif Obaid Alzaabi', class: 'G3', division: 'C' },
{ name: 'Nahyan Abdulla Salem Naser', class: 'G3', division: 'C' },
{ name: 'Nahyan Ali Hosen Farzanah', class: 'G3', division: 'C' },
{ name: 'Noura Rashed Hamad Aldhaheri', class: 'G3', division: 'C' },
{ name: 'Obaid Rashed Saeed Alshemeili', class: 'G3', division: 'C' },
{ name: 'Rawdah Ali Taleb Alkatheeri', class: 'G3', division: 'C' },
{ name: 'Saad Zebian', class: 'G3', division: 'C' },
{ name: 'Saif Fahad Hussain Almarzooqi', class: 'G3', division: 'C' },
{ name: 'Saif Sahel Bassout', class: 'G3', division: 'C' },
{ name: 'Salama Radwan Shahin Alharmi', class: 'G3', division: 'C' },
{ name: 'Salama Saddeeq Abdulla Almarzooqi', class: 'G3', division: 'C' },
{ name: 'Shahad Jumaa Mohamed Alkaabi', class: 'G3', division: 'C' },
{ name: 'Shamma Ali Hadeed Aljneibi', class: 'G3', division: 'C' },
{ name: 'Shikha Fahad Yousef Alnuaimi', class: 'G3', division: 'C' },
{ name: 'Sultan Mohamed Saleh Alhosani', class: 'G3', division: 'C' },
{ name: 'Theyab Faisal Farid Alblooshi', class: 'G3', division: 'C' },
{ name: 'Aldana Abdelrahim Ibrahim Alhosani', class: 'G3', division: 'D' },
{ name: 'Ali Khalfan Khamis Almarzooqi', class: 'G3', division: 'D' },
{ name: 'Alia Mohammed Gamal Almekhlafi', class: 'G3', division: 'D' },
{ name: 'Alya Hashim Ahmed Alhammadi', class: 'G3', division: 'D' },
{ name: 'Amal Rashed Abdulla Alshehhi', class: 'G3', division: 'D' },
{ name: 'Dhabia Ahmed Khamis Alkalbani', class: 'G3', division: 'D' },
{ name: 'Hamad Mubarak Alhamumi', class: 'G3', division: 'D' },
{ name: 'Hamad Tameem Hamad Almazrouei', class: 'G3', division: 'D' },
{ name: 'Hamdan Mohamed Ali Alhammadi', class: 'G3', division: 'D' },
{ name: 'Haya Ziad Alhaj Ali', class: 'G3', division: 'D' },
{ name: 'Hessa Husain Aqeel Almehairbi', class: 'G3', division: 'D' },
{ name: 'Hoor Adel Abdulla Aljaberi', class: 'G3', division: 'D' },
{ name: 'Humaid Abdulla Hasan Almarzooqi', class: 'G3', division: 'D' },
{ name: 'Ibrahim Omar Alnuaimi', class: 'G3', division: 'D' },
{ name: 'Joud Talib Fahad Alajmi', class: 'G3', division: 'D' },
{ name: 'Karam Abdul Khalek', class: 'G3', division: 'D' },
{ name: 'Khaled Abdulaziz Khaled Almenhali', class: 'G3', division: 'D' },
{ name: 'Khalifa Khalid Almqeemi', class: 'G3', division: 'D' },
{ name: 'Lara Abdullah Mohammad Jamous', class: 'G3', division: 'D' },
{ name: 'Mahra Abdulaziz Ali Almansoori', class: 'G3', division: 'D' },
{ name: 'Mansoor Ali Ahmed Alhammami', class: 'G3', division: 'D' },
{ name: 'Meera Khaled Anees Alhashmi', class: 'G3', division: 'D' },
{ name: 'Mohammed Salem Mubarak Almenhali', class: 'G3', division: 'D' },
{ name: 'Nahyan Humaid Husain Alhosani', class: 'G3', division: 'D' },
{ name: 'Reem Amer Mohamed Alhammadi', class: 'G3', division: 'D' },
{ name: 'Saif Sultan Dahi Alhassani', class: 'G3', division: 'D' },
{ name: 'Salama Salem Mohamed Alalawi', class: 'G3', division: 'D' },
{ name: 'Shamma Hasan Mohamed Almarzooqi', class: 'G3', division: 'D' },
{ name: 'Zayed Mohamed Abdulla Alharthi', class: 'G3', division: 'D' },
{ name: 'Zayed Sultan Dahi Alhassani', class: 'G3', division: 'D' },
{ name: 'Aldana Mohamed Abdulaziz Alseiari', class: 'G3', division: 'E' },
{ name: 'Alia Ramzi Husain Alawi Alkaf', class: 'G3', division: 'E' },
{ name: 'Almazan Ali Saleh Almansoori', class: 'G3', division: 'E' },
{ name: 'Amna Hamad Yousef Albeshr', class: 'G3', division: 'E' },
{ name: 'Fatema Awadh Ibrahim Alkaabi', class: 'G3', division: 'E' },
{ name: 'Gayah Mansoor Ahmed Alharthi', class: 'G3', division: 'E' },
{ name: 'Ghaliya Khaled Saeed Alseyabi', class: 'G3', division: 'E' },
{ name: 'Hind Darwish Ali Alyammahi', class: 'G3', division: 'E' },
{ name: 'Hoor Hamad Saeed Alshkeili', class: 'G3', division: 'E' },
{ name: 'Khalid Faisal Alebri', class: 'G3', division: 'E' },
{ name: 'Lana Abdulla Faisal Alamoodi', class: 'G3', division: 'E' },
{ name: 'Mansoor Omar Almemari', class: 'G3', division: 'E' },
{ name: 'Mariam Yousef Humaid Saleh', class: 'G3', division: 'E' },
{ name: 'Mohamed Jasim Mohamed Alhosani', class: 'G3', division: 'E' },
{ name: 'Mohamed Majed Saad Almenhali', class: 'G3', division: 'E' },
{ name: 'Mohamed Mansour Husain Alhashmi', class: 'G3', division: 'E' },
{ name: 'Nahyan Mohamed Zaid Alafeefi', class: 'G3', division: 'E' },
{ name: 'Nouf Abdulrahman Almarzooqi', class: 'G3', division: 'E' },
{ name: 'Reem Hamad Humaid Almenhali', class: 'G3', division: 'E' },
{ name: 'Saeed Abdulla Saeed Alhajeri', class: 'G3', division: 'E' },
{ name: 'Saeed Bakheet Alrashdi', class: 'G3', division: 'E' },
{ name: 'Saeed Saleh Humaid Almansoori', class: 'G3', division: 'E' },
{ name: 'Saif Abdulla Mohamed Alhashmi', class: 'G3', division: 'E' },
{ name: 'Salamh Abdalla Mohamed Alali', class: 'G3', division: 'E' },
{ name: 'Sara Ali Musallam Albreiki', class: 'G3', division: 'E' },
{ name: 'Shamma Helal Ali Aldhanhani', class: 'G3', division: 'E' },
{ name: 'Teeb Abdulaziz Saleh Alhashmi', class: 'G3', division: 'E' },
{ name: 'Theyab Sultan Alghafri', class: 'G3', division: 'E' },
{ name: 'Wadeema Mohamed Mahmood Alhussaini', class: 'G3', division: 'E' },
{ name: 'Zayed Saleh Abdelkarim Almaazmi', class: 'G3', division: 'E' },
{ name: 'Adel Aamir Alblooshi', class: 'G3', division: 'F' },
{ name: 'Aldana Ahmed Mahmoud Alhammadi', class: 'G3', division: 'F' },
{ name: 'Alreem Ahmed Abdulla Aljunibi', class: 'G3', division: 'F' },
{ name: 'Athari Abdulla Mohamed Alsuwaidi', class: 'G3', division: 'F' },
{ name: 'Awadh Suhail Ahmed Alharbi', class: 'G3', division: 'F' },
{ name: 'Darwesh Sultan Darwish Alkhemeiri', class: 'G3', division: 'F' },
{ name: 'Fatima Abdulziz Hasan Alhosani', class: 'G3', division: 'F' },
{ name: 'Ghala Adel Abedrabu Alhemeiri', class: 'G3', division: 'F' },
{ name: 'Haifa Abdulla Mahmoud Alsheebani', class: 'G3', division: 'F' },
{ name: 'Hamed Jasem Mohammed Alteneiji', class: 'G3', division: 'F' },
{ name: 'Hazza Ali Salem Almanea', class: 'G3', division: 'F' },
{ name: 'Hind Eqab Abdulla Almessabi', class: 'G3', division: 'F' },
{ name: 'Humaid Husain Ibrahim Alhammadi', class: 'G3', division: 'F' },
{ name: 'Khaled Abdulla Aqeel Alshehhi', class: 'G3', division: 'F' },
{ name: 'Khalifa Khaled Daiban', class: 'G3', division: 'F' },
{ name: 'Maitha Ali Suliman Alshehhi', class: 'G3', division: 'F' },
{ name: 'Maitha Ismaeil Hasan Alhosani', class: 'G3', division: 'F' },
{ name: 'Mariam Ali Ibrahim Almarzooqi', class: 'G3', division: 'F' },
{ name: 'Mariam Mohamed Aldhanhani', class: 'G3', division: 'F' },
{ name: 'Mera Mohamed Jasam Alhammadi', class: 'G3', division: 'F' },
{ name: 'Mohammed Ahmed Hamood Almahtasap', class: 'G3', division: 'F' },
{ name: 'Moza Abdulsalam Hasan Aljaeedi', class: 'G3', division: 'F' },
{ name: 'Nasser Khaled Ahmed Alali', class: 'G3', division: 'F' },
{ name: 'Reem Rageh Abdulqawi Alamodi', class: 'G3', division: 'F' },
{ name: 'Salama Omar Almemari', class: 'G3', division: 'F' },
{ name: 'Salma Abdulrahman Mohamed Alharthi', class: 'G3', division: 'F' },
{ name: 'Shamma Sultan Abdulrahman Alhosani', class: 'G3', division: 'F' },
{ name: 'Sultan Mohamed  Alsuwaidi', class: 'G3', division: 'F' },
{ name: 'Tanaf Mohamed Eidha Almenhali', class: 'G3', division: 'F' },
{ name: 'Wdeema Hazzaa Saif Almemari', class: 'G3', division: 'F' },
{ name: 'Ahmed Abdulrahim Ahmed Alamoodi', class: 'G3', division: 'G' },
{ name: 'Ahmed Naji Abdulla Alhosani', class: 'G3', division: 'G' },
{ name: 'Alreem Salem Saleh Almahri', class: 'G3', division: 'G' },
{ name: 'Azzan Jaafar Azzan Alkatheeri', class: 'G3', division: 'G' },
{ name: 'Fatima Hamad Mohamed Albreiki', class: 'G3', division: 'G' },
{ name: 'Ghadier Abdulla Hussain Alhuthaifi', class: 'G3', division: 'G' },
{ name: 'Hamed Omar Mohamed Alhammadi', class: 'G3', division: 'G' },
{ name: 'Khaled Ahmed Basalman', class: 'G3', division: 'G' },
{ name: 'Khaled Mohamed Ismaeel Alali', class: 'G3', division: 'G' },
{ name: 'Lateifah Hamad  Ali Aldhanhani', class: 'G3', division: 'G' },
{ name: 'Mansoor Ahmed Alhadhrami', class: 'G3', division: 'G' },
{ name: 'Mariam Abdulla Saleh Binzubaa', class: 'G3', division: 'G' },
{ name: 'Maryam Jaafar Alhashmi', class: 'G3', division: 'G' },
{ name: 'Mohamed Abdulaziz Aljuaidi', class: 'G3', division: 'G' },
{ name: 'Mohamed Abdulla Alhammadi', class: 'G3', division: 'G' },
{ name: 'Mohamed Abdulla Shams Almarzooqi', class: 'G3', division: 'G' },
{ name: 'Mohamed Ibrahim Mohamed Alhammadi', class: 'G3', division: 'G' },
{ name: 'Mohammed Adel Abdulla Aljaberi', class: 'G3', division: 'G' },
{ name: 'Nasser Yousif Malalla Alhammadi', class: 'G3', division: 'G' },
{ name: 'Nouf Faisal Mubarak Aljneibi', class: 'G3', division: 'G' },
{ name: 'Rashed Mohamed Almarri', class: 'G3', division: 'G' },
{ name: 'Saif Ali Mohamed Alhammadi', class: 'G3', division: 'G' },
{ name: 'Salama Mohamed Mansoor Almenhali', class: 'G3', division: 'G' },
{ name: 'Salama Mohamed Yousif Alhammadi', class: 'G3', division: 'G' },
{ name: 'Shahad Nasir Aldoud', class: 'G3', division: 'G' },
{ name: 'Shamsa Mohamed Jasim Alhosani', class: 'G3', division: 'G' },
{ name: 'Sultan Abdulla Mohamed Alhashmi', class: 'G3', division: 'G' },
{ name: 'Sultan Rashed Saeed Alremeithi', class: 'G3', division: 'G' },
{ name: 'Turki Ghalib Yousif Aldhuhoori', class: 'G3', division: 'G' },
{ name: 'Abdulla Fares Abdulla Alharthi', class: 'G4', division: 'G' },
{ name: 'Abdulla Mahmood Mohamed Alhammadi', class: 'G4', division: 'G' },
{ name: 'Abdullah Helal Alhadhrami', class: 'G4', division: 'G' },
{ name: 'Abrar Saleh Ismaeil Alhashmi', class: 'G4', division: 'G' },
{ name: 'Ahmad Mohamed Ismaeel Alali', class: 'G4', division: 'G' },
{ name: 'Alreem Salem Dhafer Alhajeri', class: 'G4', division: 'G' },
{ name: 'Dana Adnan Saeed Alnakhlani', class: 'G4', division: 'G' },
{ name: 'Faris Ahmed Mohamed Ashour', class: 'G4', division: 'G' },
{ name: 'Hamad Sultan Ahmed Almarzooqi', class: 'G4', division: 'G' },
{ name: 'Joud Husain Naser Alhayeed', class: 'G4', division: 'G' },
{ name: 'Maha Mohamed Yousef Almarzooqi', class: 'G4', division: 'G' },
{ name: 'Maria Mahdi Almasri', class: 'G4', division: 'G' },
{ name: 'Mariam Khaled Saeed Alobeidli', class: 'G4', division: 'G' },
{ name: 'Marya Saif Mohamed Alhammadi', class: 'G4', division: 'G' },
{ name: 'Maryam Khaled Rashed Alzaabi', class: 'G4', division: 'G' },
{ name: 'Meera Naser Saeed Alhemeiri', class: 'G4', division: 'G' },
{ name: 'Meznah Ahmed Husain Almessabi', class: 'G4', division: 'G' },
{ name: 'Mohamad Khalifa Mohamad Alhosani', class: 'G4', division: 'G' },
{ name: 'Mohamed Fares Hussain Alakberi', class: 'G4', division: 'G' },
{ name: 'Mohamed Salah Sami Ali', class: 'G4', division: 'G' },
{ name: 'Noor Yasser Humaidan', class: 'G4', division: 'G' },
{ name: 'Salem Mohamed Alhassani', class: 'G4', division: 'G' },
{ name: 'Sara Ahmed Abdulla Alhammadi', class: 'G4', division: 'G' },
{ name: 'Shaikha Falah Naser Alawlaqi', class: 'G4', division: 'G' },
{ name: 'Shamsa Majed Alblooshi', class: 'G4', division: 'G' },
{ name: 'Sulaiman Khaled Sulaiman Almewali', class: 'G4', division: 'G' },
{ name: 'Yassin Abdelazim Sayed Abdelazim', class: 'G4', division: 'G' },
{ name: 'Yousef Ahmed Hamed Alaydaroos', class: 'G4', division: 'G' },
{ name: 'Zayed Adel Abdoh Alameri', class: 'G4', division: 'G' },
{ name: 'Zayed Salem Mohamed Albreiki', class: 'G4', division: 'G' },

  // كمل باقي الأسماء بنفس التنسيق
];

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') return res.status(405).end();

  await connectDB();

  try {
    const result = await Student.insertMany(students);
    res.status(201).json({ inserted: result.length });
  } catch (error) {
    res.status(500).json({ error: 'Failed to insert students' });
  }
}
